### PR TITLE
[MPIR-361] Fix checkstyle errors after chekstyle update

### PR DESCRIPTION
**Pull request by slachiewicz**

### CODE REVIEW

**Comment by khmarbaise** [comment]
Hi, could you please have a look here: 
https://builds.apache.org/view/M-R/view/Maven/job/maven-box/job/maven-project-info-reports-plugin/job/MPIR-361/2/console
furthermore https://issues.apache.org/jira/browse/MPIR-361
That means the branch for this issue is already there and build fails based on other reasons...
```
[windows-jdk9] [ERROR] Failed to execute goal org.codehaus.mojo:keytool-maven-plugin:1.0:genkey (init) on project maven-project-info-reports-plugin: Result of cmd.exe /X /C '"f:\jenkins\tools\java\latest9\..\bin\keytool.exe -genkey -dname "cn=jetty, ou=jetty, L=Unknown, ST=Unknown, o=Apache, c=Unknown" -alias apache -keypass apache -keystore f:\jenkins\jenkins-slave\workspace\nfo-reports-plugin_MPIR-361-USOHCFAWZ4BXXFD3QLHLQ2HOCUSPDFM5URQGLU7AUHHJFZBJBXTQ\m/target/jetty.jks -storepass apache -validity 365 -keyalg RSA"' execution is: '1': The system cannot find the path specified.. -> [Help 1]
```

**Comment by slachiewicz** [comment]
With upgrade of keytool plugin, looks like problem is partialy resolved [MPIR-365](https://issues.apache.org/jira/browse/MPIR-365)
 #2

**Comment by jira-importer** [comment]
Resolve #213

**Comment by jira-importer** [comment]
Resolve #213

**Pull request closed without merging**
