### PR TITLE
[MPIR-380] contributor email rendering is fixed

### PR DESCRIPTION
**Pull request by solomax**

### CODE REVIEW

**Comment by solomax** [comment]
Can this PR be merged?
Are there any estimate for release date? :)

**Comment by rfscholte** [comment]
https://builds.apache.org/job/maven-box/job/maven-project-info-reports-plugin/job/MPIR-380/ isn't happy. Seems to be a [code convention issue](https://maven.apache.org/developers/conventions/code.html).

**Comment by solomax** [comment]
Thanks @rfscholte,
should be fixed now

**Comment by jira-importer** [comment]
Resolve #231

**Pull request merged**
