### PR TITLE
[MPIR-404] accept invalid mailing list links

### PR DESCRIPTION
**Pull request by kwin**

### CODE REVIEW

**Comment by michael-o** [comment]
Thanks, will take a look at it this week.

**Comment by michael-o** [comment]
I wonder whether this should be validated in [here](https://github.com/apache/maven/blob/master/maven-model-builder/src/main/java/org/apache/maven/model/validation/DefaultModelValidator.java) with a warning addtionally to your PR for Maven 4.

**Comment by michael-o** [comment]
@rfscholte WDYT about this?

**Comment by kwin** [comment]
> I wonder whether this should be validated in [here](https://github.com/apache/maven/blob/master/maven-model-builder/src/main/java/org/apache/maven/model/validation/DefaultModelValidator.java) with a warning additionally to your PR for Maven 4.

Seems reasonable, at the same time contributors->contributor->email should be validated (https://github.com/apache/maven-fluido-skin/blob/33156e6ee77b9c52b3345c9de0142bc54c817aba/pom.xml#L96) ;-)

**Comment by michael-o** [comment]
> 
> 
> > I wonder whether this should be validated in [here](https://github.com/apache/maven/blob/master/maven-model-builder/src/main/java/org/apache/maven/model/validation/DefaultModelValidator.java) with a warning additionally to your PR for Maven 4.
> 
> Seems reasonable, at the same time contributors->contributor->email and developers->developer->email should be validated (https://github.com/apache/maven-fluido-skin/blob/33156e6ee77b9c52b3345c9de0142bc54c817aba/pom.xml#L96) ;-)

Correct.

**Comment by michael-o** [comment]
I have current no capacities to process this. You have a workaround for this for now. I will try to pick up next month.

**Comment by jira-importer** [comment]
Resolve #255

**Pull request closed without merging**
