### PR TITLE
[MPIR-373][MPIR-374] Log Warning of incorrect dependency only on debug and add info otherw…

### PR DESCRIPTION
**Pull request by agaengel**
…ise (MPIR-373/MPIR-374)

### CODE REVIEW

**Comment by danielwegener** [comment]
Is there any way to accelerate the merge of this fix/bugfix release?

**Comment by danielwegener** [comment]
Thanks for your quick reponse @michael-o, that's awesome!

**Comment by michael-o** [comment]
ASF JIRA is currently down for maintenance. We have to wait a bit.

**Comment by michael-o** [comment]
JIRA is back online...looking into.

**Comment by slavb18** [comment]
When this PR will be released?

**Pull request closed without merging**
