### PR TITLE
[MPIR-462] IT for MR-jar troubling `:dependencies` goal

### PR DESCRIPTION
**Pull request by pzygielo**
This is reproducer for [MPIR-462](https://issues.apache.org/jira/browse/MPIR-462) but modified to pass with current implementation (by setting expected result to be _failure_ and checking some messages in `build.log`).

### CODE REVIEW

**Comment by michael-o** [comment]
Verified this locally with a snapshot. Does what intended. Will merge when Maven Shared JAR 3.1.1 is merged.

**Comment by pzygielo** [comment]
> Verified this locally with a snapshot. Does what intended. Will merge when Maven Shared JAR 3.1.1 is merged.

Just making sure.
With updated maven-shared-jar - in the current state the new IT should fail. Or do you mean - _Verified this_ modified - with TODOs done?

**Comment by michael-o** [comment]
> > Verified this locally with a snapshot. Does what intended. Will merge when Maven Shared JAR 3.1.1 is merged.
> 
> Just making sure. With updated maven-shared-jar - in the current state the new IT should fail. Or do you mean - _Verified this_ modified - with TODOs done?

Sure, cherry-picked your commit on top of https://github.com/apache/maven-project-info-reports-plugin/tree/maven-shared-jar-3.1.1 with the TODO resolved.

**Comment by pzygielo** [comment]
- Closing in favour of more complete #74

**Pull request closed without merging**
