### PR TITLE
[MPIR-432] upgrade to parent POM 39

### PR DESCRIPTION
**Pull request by elharo**

### CODE REVIEW

**Comment by slawekjaranowski** [comment]
Please check for duplicate license headers:

```
git grep -c "Licensed to the Apache Software Foundation (ASF) under one" | grep -v ":1"
```

**Comment by slawekjaranowski** [comment]
interesting build error on JDK 11

```
Error:  Step 'palantir-java-format' found problem in 'src/main/java/org/apache/maven/report/projectinfo/dependencies/renderer/DependenciesRenderer.java':
No enum constant javax.lang.model.element.Modifier.SEALED
```

I have not seen before such ...

**Comment by elharo** [comment]
Fixed the duplicate licenses. The Modifier.SEALED problem remains. I am really not happy with the palantir-java-format. It seems quite buggy and unreliable. I wonder if google-java-format is better? This problem could mean that palantir-java-format is looking at the byte code and getting confused about VM versions.

**Comment by elharo** [comment]
https://github.com/google/google-java-format/issues/697

**Review by slawekjaranowski — APPROVED** [review]

**Comment by slawekjaranowski** [comment]
discovered `palantir-java-format` issue  https://github.com/palantir/palantir-java-format/issues/865

**Comment by jira-importer** [comment]
Resolve #281

**Comment by jira-importer** [comment]
Resolve #281

**Pull request merged**
